[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/js/*.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/pages/*.html"
  [headers.values]
    Cache-Control = "no-cache"
